leftwm-theme install "Coffee"
leftwm-theme install "Orange Forest"
leftwm-theme install "Soothe"
leftwm-theme install "TNG"
leftwm-theme install "Windows XP"
leftwm-theme install "Dracula Rounded"
leftwm-theme install "Forest"
leftwm-theme install "Ground Zero"
leftwm-theme install "Red Moon"
leftwm-theme install "Blue Coffee"
leftwm-theme install "sunflower"
leftwm-theme install "Bumblebee"
leftwm-theme install "Changed Sunset"
leftwm-theme install "Garden"
leftwm-theme install "Epitaph"
leftwm-theme install "Ocean-night"
leftwm-theme install "Flamingo"
leftwm-theme install "Sunset"
leftwm-theme install "Amber"
leftwm-theme install "Catppuccin"
leftwm-theme install "Molese"
leftwm-theme install "docky"
leftwm-theme install "eden"
leftwm-theme install "material"
leftwm-theme install "mesh"
leftwm-theme install "matrix"
leftwm-theme install "parker"
leftwm-theme install "pi"
leftwm-theme install "shades"
leftwm-theme install "space"
leftwm-theme install "starwars"
leftwm-theme install "smooth"
leftwm-theme install "forest"
leftwm-theme install "grayblocks"
leftwm-theme install "greyblocks"
leftwm-theme install "halo"
leftwm-theme install "db"
leftwm-theme install "db-scifi-star"
leftwm-theme install "doublebar"
leftwm-theme install "db-color-dev"
leftwm-theme install "db-scifi"
leftwm-theme install "db-labels"
